---
title: "Improved Drinking Water Source in India"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rgdal::readOGR
```

```{r libraries, include=FALSE}
library(maps)
library(maptools)
library(rgdal)
```

## Introduction




## Cleaning And Importing Data
```{r datacleaning, cache=FALSE}
data <-read.csv("states_improved_water_source_percentages.csv")
data$four<-data$Percent_with_improved_water...4
data$four<-data$four/100
data$three<-data$Percent_with_improved_water...3
data$three<-data$three/100
```



```{r NFHS-3, echo=FALSE, warning=FALSE}
ind<- readShapePoly("IND_adm/IND_adm1", 
                    proj4string =CRS("+proj=aea +lat_1=28 +lat_2=12 +lat_0=20 +lon_0=78 +x_0=2000000 +y_0=2000000 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"))
pickColor <- function(x) {
  if (is.na(x)) {
    col <- "#ffffff"
  }
  else if (x < 0.5) {
    col <- "#f0f0f0"
  }
  else if (x < 0.6) {
    col <- "#cecece"
  }
  else if (x < 0.7) {
    col <- "#bdbdbd"
  }
  else if (x < .8) {
    col <- "#a5a5a5"
  }
  else if (x < .9) {
    col <- "#939393"
  }
  else {
    col <- "#636363"
  }
  return(col)
}

data$col <- sapply(data$three, pickColor)

plot(ind, col=data$col, border="#ffffff", lwd=0.5,  main="NFHS-3")

par(new=TRUE, plt=c(0.1, 0.25, .35, .5))
plot(0:1, 0:1, type="n", xlab="", ylab="", asp=1, axes=FALSE)
col <- c("#ffffff", "#f0f0f0", "#cecece", "#bdbdbd", "#a5a5a5","#939393", "#636363")
breaks <- c(2,3,4,5,6,7)
rect_width <- 1 / length(col)
xleft <- 0:(length(col)-1) * rect_width
ybottom <- rep(.1, length(col))
xright <- 1:length(col) * rect_width
ytop <- rep(.2, length(col))
rect(xleft, ybottom, xright, ytop, col=col, border="#e0e0e0", lwd=.5)
text(.5, .35, "HH with Improved\n Drinking Water Source", cex=.5)
text(1:(length(col)-1) * rect_width, .04, labels = breaks, cex=0.7)



```
```{r NFHS-4, echo=FALSE, warning=FALSE}
data$col <- sapply(data$four, pickColor)

plot(ind, col=data$col, border="#ffffff", lwd=0.5,  main="NFHS-4")

par(new=TRUE, plt=c(0.1, 0.25, .35, .5))
plot(0:1, 0:1, type="n", xlab="", ylab="", asp=1, axes=FALSE)
col <- c("#ffffff", "#f0f0f0", "#cecece", "#bdbdbd", "#a5a5a5","#939393", "#636363")
breaks <- c(2,3,4,5,6,7)
rect_width <- 1 / length(col)
xleft <- 0:(length(col)-1) * rect_width
ybottom <- rep(.1, length(col))
xright <- 1:length(col) * rect_width
ytop <- rep(.2, length(col))
rect(xleft, ybottom, xright, ytop, col=col, border="#e0e0e0", lwd=.5)
text(.5, .35, "HH with Improved\n Drinking Water Source", cex=.5)
text(1:(length(col)-1) * rect_width, .04, labels = breaks, cex=0.7)
```

